steps:
  # 1. Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/veracity-backend",
        "-f",
        "backend/Dockerfile",
        ".",
      ]

  # 2. Push the image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/veracity-backend"]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "veracity-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/veracity-backend"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      # This links the GCP Secret to the Env Var name NestJS expects
      - "--set-secrets"
      - "FRONTEND_URL=FRONTEND_URL:latest,PORT=PORT:latest"

images:
  - "gcr.io/$PROJECT_ID/veracity-backend"
