import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { TanStackRouterDevtools } from "@tanstack/router-devtools";

import { routeTree } from "./routeTree.gen"; // Auto-generated by the plugin
import "./index.css";

// 1. Initialize the router
const router = createRouter({ routeTree });

// 2. Register the router for type safety in navigation
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    {/* 3. Wrap your app with the RouterProvider */}
    <RouterProvider router={router} />
    <TanStackRouterDevtools />
  </StrictMode>,
);